#ifndef _ESC_H__
#define _ESC_H__

typedef struct {
	char			*opr;
	unsigned short	code;
} OPRLIST;

enum {
	ESC_B=64,
	ESC_BT,
	ESC_BC,
	ESC_BCT,
	ESC_BD,
	ESC_BR,
	ESC_BF,
	ESC_V,
	ESC_H,

	ESC_S,
	ESC_Z,
	ESC_FI,
	ESC_FIF,
	ESC_FO,
	ESC_FOF,
	ESC_FB,
	ESC_PFI,
	ESC_PFO,
	ESC_PWI,
	ESC_PWO,

	ESC_Q,
	ESC_F,

	ESC_C,
	ESC_CR,
	
	ESC_CP,
	ESC_CL,
	ESC_CY,
	ESC_CB,
	ESC_CA,
	ESC_CW,
	ESC_CRW,

	ESC_W,
	ESC_WR,

	ESC_KW,
	ESC_K,

	ESC_M,
	ESC_MS,
	ESC_MP,
	ESC_MV,
	ESC_MW,

	ESC_SE,
	ESC_SEP,
	ESC_SES,
	ESC_SEW,
	ESC_SEV,
	ESC_SEVW,

	ESC_R,
	ESC_RC,
	ESC_RR,

	ESC_LF,

	ESC_WE,
	ESC_WER,

	ESC_SETFLAG,
	ESC_GETFLAG,

	ESC_SETGAMEFLAG,
	ESC_GETGAMEFLAG,

	ESC_LOADSCRIPT,
	ESC_GAMEEND,
	ESC_CALLFUNC,

	ESC_SETTIMEMODE,
	ESC_SETTIMEBACK,
	ESC_SETTIMECHAR,

	ESC_SETMATRIX,
	ESC_SHOWCHIPBACK,
	ESC_POSECHIPBACK,
	ESC_PLAYCHIPBACK,

	ESC_SETCHIPBACK,
	ESC_SETCHIPPARTS,
	ESC_SETCHIPSCROLL,
	ESC_SETCHIPSCROLL2,
	ESC_SETCHIPSCROLLSPEED,
	ESC_WAITCHIPSCROLL,
	ESC_WAITCHIPSCROLLSPEED,

	ESC_SETCHIPCHARCASH,
	ESC_RESETCHIPCHARCASH,

	ESC_SETCHIPCHAR,
	ESC_SETCHIPCHARANI,
	ESC_RESETCHIPCHAR,
	ESC_SETCHIPCHARPARAM,
	ESC_SETCHIPCHARBRIGHT,
	ESC_SETCHIPCHARMOVE,
	ESC_SETCHIPCHARMOVE2,
	ESC_SETCHIPCHARMOVESPEED,
	ESC_GETCHIPCHARMOVE,
	ESC_GETCHIPCHARMOVESPEED,
	ESC_COPYCHIPCHARPOS,
	ESC_SETCHIPCHARREV,
	ESC_THROUGHCHIPCHARANI,
	ESC_WAITCHIPCHARREPEAT,
	ESC_WAITCHIPCHARANI,
	ESC_WAITCHIPCHARANILOOP,
	ESC_WAITCHIPCHARAMOVE,

	ESC_GETBACK,
	ESC_SETBACK,
	ESC_SETBACK2,
	ESC_SETCG,
	ESC_SETCG2,
	ESC_SETBACKPOS,
	ESC_SETBACKPOSZ,
	ESC_SETBACKSCROLL,
	ESC_SETBACKSCROLLZ,
	ESC_SETBACKCSCOPE,
	ESC_WAITBACKCSCOPE,
	ESC_LOCKBACKCSCOPE,
	ESC_SETBACKFADEIN,
	ESC_SETBACKFADEOUT,
	ESC_SETBACKFADERGB,

	ESC_SETSHAKE,
	ESC_STOPSHAKE,

	ESC_SETFLASH,

	ESC_SETCHAR,
	ESC_RESETCHAR,
	ESC_SETCHARPOSE,
	ESC_SETCHARLOCATE,
	ESC_SETCHARLAYER,
	ESC_WAITCHAR,

	ESC_SETBLOCK,
	ESC_SETWINDOW,
	ESC_RESETWINDOW,

	ESC_SETMESSAGE,
	ESC_SETMESSAGE2,
	ESC_SETMESSAGEEX,
	ESC_SETCHIPMESSAGE,
	ESC_ADDMESSAGE,
	ESC_ADDMESSAGE2,
	ESC_SETMESSAGEWAIT,
	ESC_RESETMESSAGE,

	ESC_WAITKEY,

	ESC_SETSELECTMES,
	ESC_SETSELECTMESEX,
	ESC_SETSELECT,
	ESC_SETSELECTEX,

	ESC_PLAYBGM,
	ESC_PLAYBGMEX,
	ESC_STOPBGM,
	ESC_STOPBGMEX,
	ESC_SETVOLUMEBGM,
	ESC_SETVOLUMEBGMEX,

	ESC_PLAYSE,
	ESC_PLAYSEEX,
	ESC_STOPSEEX,
	ESC_SETVOLUMESE,

	ESC_SETWEATHER,
	ESC_CHANGEWEATHER,
	ESC_RESETWEATHER,
	ESC_SETLENSFREA,
	ESC_SETWAVEFFECT,
	ESC_RESETWAVEFFECT,

	ESC_WAITFRAME,

	ESC_SETBMP,
	ESC_SETBMP4BMP,
	ESC_SETBMPPRIM,
	ESC_RESETBMP,
	ESC_RESETBMPALL,
	ESC_SETBMPANIME,
	ESC_RESETBMPANIME,
	ESC_WAITBMPANIME,
	ESC_SETTITLE,
	ESC_SETENDING,
	ESC_SETAVI,
	ESC_RESETAVI,
	ESC_WAITAVI,
	ESC_SETAVIFULL,
	ESC_WAITAVIFULL,

	ESC_SETBMPDISP,
	ESC_SETBMPLAYER,
	ESC_SETBMPPARAM,
	ESC_SETBMPREVPARAM,
	ESC_SETBMPBRIGHT,
	ESC_SETBMPMOVE,
	ESC_SETBMPPOS,
	ESC_SETBMPZOOM,
	ESC_SETBMPZOOM2,
	ESC_SETBMPANIMEPLAY,

	ESC_SETDEMOFLAG,
	ESC_SETSCENENO,
	ESC_SETENDINGNO,
	ESC_SETREPLAYNO,

	ESC_SETSOUNDEVENT,
	ESC_SETSOUNDEVENTVOLUME,

	ESC_SETPOTAPOTA,

	ESC_GETTIME,
	ESC_WAITTIME,
	ESC_STANDBYTIME,

	ESC_SETTEXTFORMAT,
	ESC_SETTEXTSYNC,
	ESC_SETTEXT,
	ESC_SETTEXTEX,
	ESC_RESETTEXT,
	ESC_WAITTEXT,
	ESC_RESETTEXTALL,

	ESC_SETDEMOFADEFLAG,
	
	ESC_MOV2,
	ESC_SETCUTCUT,

	ESC_SETNOISE,
	ESC_T,

	ESC_SETUSOERR,
	ESC_LOADSCRIPTNUM,

	ESC_SETRIPPLE,
	ESC_SETRIPPLESET,
	ESC_WAITRIPPLE,

	ESC_SETRIPPLELOST,
	ESC_MLW,
	ESC_VT,
	ESC_HT,

	ESC_SETMOVIE,

	ESC_HTML,
	ESC_WINEXEC,
	ESC_KABEGAMI,
	ESC_STAFFMODE,
	ESC_STAFFROLL,

	ESC_VV,
	ESC_VA,
	ESC_VB,
	ESC_VC,
	ESC_VX,
	ESC_VW,
	ESC_VS,
	ESC_VI,

	ESC_SETNOISESCREEN,
	ESC_GETITEM,
	ESC_SETCHAPTER,
	ESC_SETROOM,
	ESC_OPR_MAX,
};

OPRLIST EventOprList[] = {

	{	"B",					ESC_B			},	
	{	"BT",					ESC_BT			},	
	{	"BC",					ESC_BC			},	
	{	"BCT",					ESC_BCT			},	
	{	"BD",					ESC_BD			},	
	{	"BR",					ESC_BR			},	
	{	"BF",					ESC_BF			},	
	{	"V",					ESC_V			},	
	{	"H",					ESC_H			},	

	{	"S",					ESC_S			},	
	{	"Z",					ESC_Z			},	
	{	"FI",					ESC_FI			},	
	{	"FIF",					ESC_FIF			},	
	{	"FO",					ESC_FO			},	
	{	"FOF",					ESC_FOF			},	
	{	"FB",					ESC_FB			},	
	{	"PFI",					ESC_PFI			},	
	{	"PFO",					ESC_PFO			},	
	{	"PWI",					ESC_PWI			},	
	{	"PWO",					ESC_PWO			},	

	{	"Q",					ESC_Q			},	
	{	"F",					ESC_F			},	

	{	"C",					ESC_C			},	
	{	"CR",					ESC_CR			},	
	{	"CP",					ESC_CP			},	
	{	"CL",					ESC_CL			},	
	{	"CY",					ESC_CY			},	
	{	"CB",					ESC_CB			},	
	{	"CA",					ESC_CA			},	
	{	"CW",					ESC_CW			},	
	{	"CRW",					ESC_CRW			},	

	{	"W",					ESC_W			},	
	{	"WR",					ESC_WR			},	

	{	"KW",					ESC_KW			},	
	{	"K",					ESC_K			},	

	{	"M",					ESC_M			},	
	{	"MS",					ESC_MS			},	
	{	"MP",					ESC_MP			},	
	{	"MV",					ESC_MV			},	
	{	"MW",					ESC_MW			},	

	{	"SE",					ESC_SE			},	
	{	"SEP",					ESC_SEP			},	
	{	"SES",					ESC_SES			},	
	{	"SEW",					ESC_SEW			},	
	{	"SEV",					ESC_SEV			},	
	{	"SEVW",					ESC_SEVW		},	

	{	"R",					ESC_R			},	
	{	"RC",					ESC_RC			},	
	{	"RR",					ESC_RR			},	

	{	"LF",					ESC_LF			},	

	{	"WE",					ESC_WE			},	
	{	"WER",					ESC_WER			},	

	{	"SetFlag",				ESC_SETFLAG			},	
	{	"GetFlag",				ESC_GETFLAG			},	

	{	"SetGameFlag",			ESC_SETGAMEFLAG		},	
	{	"GetGameFlag",			ESC_GETGAMEFLAG		},	

	{	"LoadScript",			ESC_LOADSCRIPT		},	
	{	"GameEnd",				ESC_GAMEEND			},	
	{	"CallFunc",				ESC_CALLFUNC		},	

	{	"SetTimeMode",			ESC_SETTIMEMODE		},	
	{	"SetTimeBack",			ESC_SETTIMEBACK		},	
	{	"SetTimeChar",			ESC_SETTIMECHAR		},	

	{	"SetMatrix",			ESC_SETMATRIX		},	
	{	"ShowChipBack",			ESC_SHOWCHIPBACK	},	
	{	"PoseChipBack",			ESC_POSECHIPBACK	},	
	{	"PlayChipBack",			ESC_PLAYCHIPBACK	},	

	{	"SetChipBack",			ESC_SETCHIPBACK		},	
	{	"SetChipParts",			ESC_SETCHIPPARTS	},	
	{	"SetChipScroll",		ESC_SETCHIPSCROLL	},	
	{	"SetChipScroll2",		ESC_SETCHIPSCROLL2	},	
	{	"SetChipScrollSpeed",	ESC_SETCHIPSCROLLSPEED	},	
	{	"WaitChipScroll",		ESC_WAITCHIPSCROLL		},	
	{	"WaitChipScrollSpeed",	ESC_WAITCHIPSCROLLSPEED	},	

	{	"SetChipCharCash",		ESC_SETCHIPCHARCASH		},	
	{	"ResetChipCharCash",	ESC_RESETCHIPCHARCASH	},	

	{	"SetChipChar",			ESC_SETCHIPCHAR			},	
	{	"SetChipCharAni",		ESC_SETCHIPCHARANI		},	
	{	"ResetChipChar",		ESC_RESETCHIPCHAR		},	
	{	"SetChipCharParam",		ESC_SETCHIPCHARPARAM	},	
	{	"SetChipCharBright",	ESC_SETCHIPCHARBRIGHT	},	
	{	"SetChipCharMove",		ESC_SETCHIPCHARMOVE		},	
	{	"SetChipCharMove2",		ESC_SETCHIPCHARMOVE2	},	
	{	"SetChipCharMoveSpeed",	ESC_SETCHIPCHARMOVESPEED},	
	{	"GetChipCharMove",		ESC_GETCHIPCHARMOVE		},	
	{	"GetChipCharMoveSpeed",	ESC_GETCHIPCHARMOVESPEED},	
	{	"CopyChipCharPos",		ESC_COPYCHIPCHARPOS		},	
	{	"SetChipCharRev",		ESC_SETCHIPCHARREV		},	
	{	"ThroughChipCharAni",	ESC_THROUGHCHIPCHARANI	},	
	
	{	"WaitChipCharRepeat",	ESC_WAITCHIPCHARREPEAT	},	
	{	"WaitChipCharAni",		ESC_WAITCHIPCHARANI		},	
	{	"WaitChipCharAniLoop",	ESC_WAITCHIPCHARANILOOP	},	
	{	"WaitChipCharMove",		ESC_WAITCHIPCHARAMOVE	},	

	{	"GetBack",				ESC_GETBACK			},	
	{	"SetBack",				ESC_SETBACK			},	
	{	"SetBack2",				ESC_SETBACK2		},	
	{	"SetCg",				ESC_SETCG			},	
	{	"SetCg2",				ESC_SETCG2			},	
	{	"SetBackPos",			ESC_SETBACKPOS		},	
	{	"SetBackPosZ",			ESC_SETBACKPOSZ		},	
	{	"SetBackScroll",		ESC_SETBACKSCROLL	},	
	{	"SetBackScrollZ",		ESC_SETBACKSCROLLZ	},	
	{	"SetBackCScope",		ESC_SETBACKCSCOPE	},	
	{	"WaitBackCScope",		ESC_WAITBACKCSCOPE	},	
	{	"LockBackCScope",		ESC_LOCKBACKCSCOPE	},	
	{	"SetBackFadeIn",		ESC_SETBACKFADEIN	},	
	{	"SetBackFadeOut",		ESC_SETBACKFADEOUT	},	
	{	"SetBackFadeRGB",		ESC_SETBACKFADERGB	},	

	{	"SetShake",				ESC_SETSHAKE		},	
	{	"StopShake",			ESC_STOPSHAKE		},	

	{	"SetFlash",				ESC_SETFLASH		},	

	{	"SetChar",				ESC_SETCHAR			},	
	{	"ResetChar",			ESC_RESETCHAR		},	
	{	"SetCharPose",			ESC_SETCHARPOSE		},	
	{	"SetCharLocate",		ESC_SETCHARLOCATE	},	
	{	"SetCharLayer",			ESC_SETCHARLAYER	},	
	{	"WaitChar",				ESC_WAITCHAR		},	

	{	"SetBlock",				ESC_SETBLOCK		},	
	{	"SetWindow",			ESC_SETWINDOW		},	
	{	"ResetWindow",			ESC_RESETWINDOW		},	
	{	"SetMessage",			ESC_SETMESSAGE		},	
	{	"SetMessage2",			ESC_SETMESSAGE2		},	
	{	"SetMessageEx",			ESC_SETMESSAGEEX	},	
	{	"SetChipMessage",		ESC_SETCHIPMESSAGE	},	
	
	{	"AddMessage",			ESC_ADDMESSAGE		},	
	{	"AddMessage2",			ESC_ADDMESSAGE2		},	
	{	"SetMessageWait",		ESC_SETMESSAGEWAIT	},	
	{	"ResetMessage",			ESC_RESETMESSAGE	},	

	{	"WaitKey",				ESC_WAITKEY			},	

	{	"SetSelectMes",			ESC_SETSELECTMES	},	
	{	"SetSelectMesEx",		ESC_SETSELECTMESEX	},	
	{	"SetSelect",			ESC_SETSELECT		},	
	{	"SetSelectEx",			ESC_SETSELECTEX		},	

	{	"PlayBgm",				ESC_PLAYBGM			},	
	{	"PlayBgmEx",			ESC_PLAYBGMEX		},	
	{	"StopBgm",				ESC_STOPBGM			},	
	{	"StopBgmEx",			ESC_STOPBGMEX		},	
	{	"SetVolumeBgm",			ESC_SETVOLUMEBGM	},	
	{	"SetVolumeBgmEx",		ESC_SETVOLUMEBGMEX	},	

	{	"PlaySe",				ESC_PLAYSE			},	
	{	"PlaySeEx",				ESC_PLAYSEEX		},	
	{	"StopSeEx",				ESC_STOPSEEX		},	
	{	"SetVolumeSe",			ESC_SETVOLUMESE		},	

	{	"SetWeather",			ESC_SETWEATHER		},	
	{	"ChangeWeather",		ESC_CHANGEWEATHER	},	
	{	"ResetWeather",			ESC_RESETWEATHER	},	
	{	"SetLensFrea",			ESC_SETLENSFREA		},	
	{	"SetWavEffect",			ESC_SETWAVEFFECT	},	
	{	"ResetWavEffect",		ESC_RESETWAVEFFECT	},	

	{	"WaitFrame",			ESC_WAITFRAME		},	

	{	"SetBmp",				ESC_SETBMP			},	
	{	"SetBmp4Bmp",			ESC_SETBMP4BMP		},	
	{	"SetBmpPrim",			ESC_SETBMPPRIM		},	
	{	"ResetBmp",				ESC_RESETBMP		},	
	{	"ResetBmpAll",			ESC_RESETBMPALL		},	
	{	"SetBmpAnime",			ESC_SETBMPANIME		},	
	{	"ResetBmpAnime",		ESC_RESETBMPANIME	},	
	{	"WaitBmpAnime",			ESC_WAITBMPANIME	},	
	{	"SetTitle",				ESC_SETTITLE		},	
	{	"SetEnding",			ESC_SETENDING		},	

	{	"SetAvi",				ESC_SETAVI			},	
	{	"ResetAvi",				ESC_RESETAVI		},	
	{	"WaitAvi",				ESC_WAITAVI			},	
	{	"SetAviFull",			ESC_SETAVIFULL		},	
	{	"WaitAviFull",			ESC_WAITAVIFULL		},	

	{	"SetBmpDisp",			ESC_SETBMPDISP		},	
	{	"SetBmpLayer",			ESC_SETBMPLAYER		},	
	{	"SetBmpParam",			ESC_SETBMPPARAM		},	
	{	"SetBmpRevParam",		ESC_SETBMPREVPARAM	},	
	{	"SetBmpBright",			ESC_SETBMPBRIGHT	},	
	{	"SetBmpMove",			ESC_SETBMPMOVE		},	
	{	"SetBmpPos",			ESC_SETBMPPOS		},	
	{	"SetBmpZoom",			ESC_SETBMPZOOM		},	
	{	"SetBmpZoom2",			ESC_SETBMPZOOM2		},	
	{	"SetBmpAnimePlay",		ESC_SETBMPANIMEPLAY	},

	{	"SetDemoFlag",			ESC_SETDEMOFLAG		},	
	{	"SetSceneNo",			ESC_SETSCENENO		},	
	{	"SetEndingNo",			ESC_SETENDINGNO		},	
	{	"SetReplayNo",			ESC_SETREPLAYNO		},	

	{	"SetSoundEvent",		ESC_SETSOUNDEVENT	},	
	{	"SetSoundEventVolume",	ESC_SETSOUNDEVENTVOLUME	},	

	{	"SetPotaPota",			ESC_SETPOTAPOTA		},	

	{	"GetTime",				ESC_GETTIME			},	
	{	"WaitTime",				ESC_WAITTIME		},	
	{	"StandbyTime",			ESC_STANDBYTIME		},	

	{	"SetTextFormat",		ESC_SETTEXTFORMAT	},	
	{	"SetTextSync",			ESC_SETTEXTSYNC		},	
	{	"SetText",				ESC_SETTEXT			},	
	{	"SetTextEx",			ESC_SETTEXTEX		},	
	{	"ResetText",			ESC_RESETTEXT		},	
	{	"WaitText",				ESC_WAITTEXT		},	
	{	"ResetTextAll",			ESC_RESETTEXTALL	},	

	{	"SetDemoFadeFlag",		ESC_SETDEMOFADEFLAG	},	

	{	"Mov2",					ESC_MOV2			},	
	{	"SetCutCut",			ESC_SETCUTCUT		},	


	{	"SetNoise",				ESC_SETNOISE		},	
	{	"T",					ESC_T				},	
	{	"SetUsoErr",			ESC_SETUSOERR		},	
	{	"LoadScriptNum",		ESC_LOADSCRIPTNUM	},	

	{	"SetRipple",			ESC_SETRIPPLE		},	
	{	"SetRippleSet",			ESC_SETRIPPLESET	},	
	{	"WaitRipple",			ESC_WAITRIPPLE		},	
	{	"SetRippleLost",		ESC_SETRIPPLELOST	},	
	{	"MLW",					ESC_MLW				},	

	{	"VT",					ESC_VT				},	
	{	"HT",					ESC_HT				},	

	{	"SetMovie",				ESC_SETMOVIE		},	

	{	"HTML",					ESC_HTML			},	
	{	"WinExec",				ESC_WINEXEC			},	
	{	"Kabegami",				ESC_KABEGAMI		},	
	{	"Staffmode",			ESC_STAFFMODE		},	
	{	"StaffRoll",			ESC_STAFFROLL		},	

	{	"VV",					ESC_VV			},	
	{	"VA",					ESC_VA			},	
	{	"VB",					ESC_VB			},	
	{	"VC",					ESC_VC			},	
	{	"VX",					ESC_VX			},	
	{	"VW",					ESC_VW			},	
	{	"VS",					ESC_VS			},	
	{	"VI",					ESC_VI			},	
	{	"SetNoiseScreen",		ESC_SETNOISESCREEN },	
	{	"GetItem",				ESC_GETITEM		},	
	{	"SetChapter",			ESC_SETCHAPTER	},	
	{	"SetRoom",				ESC_SETROOM		},	
	{	NULL,	ESC_OPR_MAX	},
};

#define ESC_NOT		0
#define ESC_ASC		1
#define ESC_NUM		2
#define ESC_STR		3
#define ESC_STR2	4
#define ESC_REG		5
#define ESC_CMP		6
#define ESC_ADD		7
#define ESC_CNT		8
#define ESC_VCNT	9

#define ESC_WAIT	0
#define ESC_NOWAIT	1

typedef struct{
	char	type[15];
	char	ret;
	char	default_num;
}ESCRIPT_OPR;

ESCRIPT_OPR		EScroptOpr[] = {
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 4
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 4
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 8
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 4
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},

	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},

	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
	 	 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM},
		ESC_NOWAIT, 14
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},

	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_REG, ESC_REG, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_REG, ESC_REG, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
		
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 8
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{
		{ESC_NUM, ESC_STR, ESC_CNT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_STR2,ESC_ADD, ESC_CNT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_STR, ESC_NUM, ESC_CNT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_STR, ESC_CNT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_STR2,ESC_ADD, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_STR, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_STR, ESC_STR, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 3
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},

	{
		{ESC_NUM, ESC_NUM, ESC_STR, ESC_NUM, ESC_NUM,
		 ESC_STR, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_STR, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 7
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_STR, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 3
	},

	{
		{ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 10
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{
		{ESC_REG, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 5
	},
	{
		{ESC_STR, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_STR, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},

	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
};

#endif 
