//------------------------------------------------------------------------
 //  Project Name   :  未定（仮）
  //  File Name      :  Esc.h
   //  Copyright      :  AQUA (Leaf)  since 2000 - 
    //                                 Programd by.  Miyakusa Masakazu
     //------------------------------------------------------------------------
      // ★拡張イベントスクリプト命令コード・引数（デコード・エンコード両用）ヘッダ

#ifndef _ESC_H__
#define _ESC_H__

//#ifndef ENCODE
typedef struct {
	char			*opr;
	unsigned short	code;
} OPRLIST;
//#endif//ENCODE

enum {
//**********  簡易命令  ***************************************************
	ESC_LOAD_MAP=64,
	ESC_RELEASE_MAP,

	ESC_SET_MAP_OBJ,
	ESC_SET_MAP_OBJ_EX,
	ESC_SET_MAP_OBJ_NOLOAD,

	ESC_SET_MAP_OBJ_REV,
	ESC_SET_MAP_OBJ_LAYER,
	ESC_SET_MAP_OBJ_MOVE,
	ESC_SET_MAP_OBJ_ZOOM,
	ESC_SET_MAP_OBJ_PARAM,
	ESC_PLAY_MAP_OBJ,
	ESC_RESET_MAP_OBJ,

	ESC_SET_BRIGHT_MAP,
	ESC_SET_SCROLL_MAP,
	ESC_SET_SCROLL_MAP_CHAR,
	ESC_WAIT_MAP,

	ESC_START_BATTLE,
	ESC_WAIT_BATTLE_END,
	ESC_WAIT_BATTLE_END_EX,

	ESC_SET_MAP_CHAR_PLAER,
	ESC_SET_MAP_CHAR,
	ESC_SET_MAP_CHAR_ENGUN,
	ESC_SET_MAP_CHAR_ITEM,
	ESC_SET_MAP_CHAR_THINK,
	ESC_RESET_MAP_CHAR,
	ESC_RESET_MAP_CHAR_ALL,
	ESC_SET_MAP_CHAR_EVENT,
	ESC_WAIT_MAP_CHAR_EVENT,

	ESC_SET_MAP_CHAR_MOVE,
	ESC_WAIT_MAP_CHAR_MOVE,
	ESC_SET_MAP_CHAR_DISP,


	ESC_B,
	ESC_BT,
	ESC_BC,
	ESC_BCT,
	ESC_V,
	ESC_VT,
	ESC_H,
	ESC_HT,
//
	ESC_S,
	ESC_Z,
	ESC_FI,
	ESC_FIF,
	ESC_FO,
	ESC_FOF,
	ESC_FB,
	ESC_PFI,
	ESC_PFO,
	ESC_PWI,
	ESC_PWO,
//
	ESC_Q,
	ESC_F,
//
	ESC_C,
	ESC_CR,
	
	ESC_CP,
	ESC_CL,
	ESC_CY,
	ESC_CB,
	ESC_CA,
	ESC_CW,
//
	ESC_W,
	ESC_WR,
	ESC_WN,
//
	ESC_KW,
	ESC_K,
//
	ESC_M,
	ESC_MS,
	ESC_MP,
	ESC_MV,
	ESC_MW,
//
	ESC_SE,
	ESC_SEP,
	ESC_SES,
	ESC_SEW,
	ESC_SEV,
	ESC_SEVW,
//
	ESC_VV,
	ESC_VA,
	ESC_VB,
	ESC_VC,
	ESC_VX,
	ESC_VW,
	ESC_VS,
	ESC_VI,
//
	ESC_R,
	ESC_RC,
	ESC_RR,
//
	ESC_LF,
//
	ESC_WE,
	ESC_WER,

//**********  低レベル命令  ***************************************************

	ESC_SETFLAG,
	ESC_GETFLAG,

	ESC_SETGAMEFLAG,
	ESC_GETGAMEFLAG,

	ESC_LOADSCRIPT,
	ESC_GAMEEND,
	ESC_CALLFUNC,

	ESC_SETTIMEMODE,
	ESC_SETCHROMAMODE,
	ESC_SETEFFCTMODE,

	ESC_SETMESSAGE,
	ESC_SETMESSAGE2,
	ESC_SETMESSAGEEX,
	ESC_SETCHIPMESSAGE,
	ESC_ADDMESSAGE,
	ESC_ADDMESSAGE2,
	ESC_SETMESSAGEWAIT,
	ESC_RESETMESSAGE,

	ESC_WAITKEY,

	ESC_SETSELECTMES,
	ESC_SETSELECTMESEX,
	ESC_SETSELECT,
	ESC_SETSELECTEX,

	ESC_PLAYBGM,
	ESC_PLAYBGMEX,
	ESC_STOPBGM,
	ESC_STOPBGMEX,
	ESC_SETVOLUMEBGM,
	ESC_SETVOLUMEBGMEX,

	ESC_PLAYSE,
	ESC_PLAYSEEX,
	ESC_STOPSEEX,
	ESC_SETVOLUMESE,

	ESC_SETWEATHER,
	ESC_CHANGEWEATHER,
	ESC_RESETWEATHER,
	ESC_SETLENSFREA,
	ESC_SETWAVEFFECT,
	ESC_RESETWAVEFFECT,

	ESC_SETWARP,
	ESC_RESETWARP,

	ESC_WAITFRAME,

	ESC_SETBMP,
	ESC_SETBMPEX,
	ESC_SETBMP4BMP,
	ESC_SETBMPPRIM,
	ESC_RESETBMP,
	ESC_RESETBMPALL,
	ESC_SETBMPANIME,
	ESC_RESETBMPANIME,
	ESC_WAITBMPANIME,
	ESC_SETBMPANIMEPLAY,

	ESC_SETAVI,
	ESC_RESETAVI,
	ESC_WAITAVI,
	ESC_SETAVIFULL,
	ESC_WAITAVIFULL,

	ESC_SETBMPDISP,
	ESC_SETBMPLAYER,
	ESC_SETBMPPARAM,
	ESC_SETBMPREVPARAM,
	ESC_SETBMPBRIGHT,
	ESC_SETBMPMOVE,
	ESC_SETBMPPOS,
	ESC_SETBMPZOOM,
	ESC_SETBMPZOOM2,

	ESC_SETTITLE,
	ESC_SETENDING,
	ESC_NEXTGAMESTEP,

	ESC_SETDEMOFLAG,
	ESC_SETSCENENO,
	ESC_SETENDINGNO,
	ESC_SETREPLAYNO,

	ESC_SETSOUNDEVENT,
	ESC_SETSOUNDEVENTVOLUME,

	ESC_SETPOTAPOTA,

	ESC_GETTIME,
	ESC_WAITTIME,

	ESC_SETTEXTFORMAT,
	ESC_SETTEXTSYNC,
	ESC_SETTEXT,
	ESC_SETTEXTEX,
	ESC_RESETTEXT,
	ESC_WAITTEXT,
	ESC_RESETTEXTALL,

	ESC_SETDEMOFADEFLAG,
	
	ESC_MOV2,
	ESC_SIN,
	ESC_COS,
	ESC_ABS,

	ESC_TESTSETPARAM,
	ESC_SETPARTYCHAR,

	ESC_GETPARTYLEVEL,
	ESC_SETMAPBOX,

	ESC_SETCUTCUT,

	ESC_SETNOISE,
	ESC_T,

	ESC_SETUSOERR,
	ESC_LOADSCRIPTNUM,

	ESC_SETRIPPLE,
	ESC_SETRIPPLESET,
	ESC_WAITRIPPLE,

	ESC_SETRIPPLELOST,
	ESC_MLW,


	ESC_GET_ITEM,
	ESC_CHECK_ITEM,
	ESC_SET_MAP_CHAR_NAME,
	ESC_SETBMPROLL,

	ESC_SETMOVIE,
	ESC_DEBUGBOX,

	ESC_VHFLAG,

	ESC_OPR_MAX,
};

//#ifdef MODE
OPRLIST EventOprList[] = {
/*EventOprList_Start*/

//簡易関数
	{	"LoadMap",				ESC_LOAD_MAP		},	//
	{	"ReleaseMap",			ESC_RELEASE_MAP		},	//

	{	"SetMapObj",			ESC_SET_MAP_OBJ			},
	{	"SetMapObjEx",			ESC_SET_MAP_OBJ_EX		},
	{	"SetMapObjNoLoad",		ESC_SET_MAP_OBJ_NOLOAD	},

	{	"SetMapObjRev",			ESC_SET_MAP_OBJ_REV		},
	{	"SetMapObjLayer",		ESC_SET_MAP_OBJ_LAYER	},
	{	"SetMapObjMove",		ESC_SET_MAP_OBJ_MOVE	},
	{	"SetMapObjZoom",		ESC_SET_MAP_OBJ_ZOOM	},
	{	"SetMapObjParam",		ESC_SET_MAP_OBJ_PARAM	},
	{	"PlayMapObj",			ESC_PLAY_MAP_OBJ		},
	{	"ResetMapObj",			ESC_RESET_MAP_OBJ		},

	{	"SetBrightMap",			ESC_SET_BRIGHT_MAP	},
	{	"SetScrollMap",			ESC_SET_SCROLL_MAP	},
	{	"SetScrollMapChar",		ESC_SET_SCROLL_MAP_CHAR	},
	{	"WaitMap",				ESC_WAIT_MAP	},

	{	"StartBattle",			ESC_START_BATTLE	},	//
	{	"WaitBattleEnd",		ESC_WAIT_BATTLE_END	},	//
	{	"WaitBattleEndEx",		ESC_WAIT_BATTLE_END_EX	},	//

	{	"SetMapCharPlayer",		ESC_SET_MAP_CHAR_PLAER	},
	{	"SetMapChar",			ESC_SET_MAP_CHAR		},
	{	"SetMapCharEngun",		ESC_SET_MAP_CHAR_ENGUN	},
	{	"SetMapCharItem",		ESC_SET_MAP_CHAR_ITEM	},
	{	"SetMapCharThink",		ESC_SET_MAP_CHAR_THINK	},
	{	"ResetMapChar",			ESC_RESET_MAP_CHAR		},
	{	"ResetMapCharAll",		ESC_RESET_MAP_CHAR_ALL	},

	{	"SetMapCharEvent",		ESC_SET_MAP_CHAR_EVENT	},
	{	"WaitMapCharEvent",		ESC_WAIT_MAP_CHAR_EVENT	},

	{	"SetMapCharMove",		ESC_SET_MAP_CHAR_MOVE	},
	{	"WaitMapCharMove",		ESC_WAIT_MAP_CHAR_MOVE	},
	{	"SetMapCharDisp",		ESC_SET_MAP_CHAR_DISP	},
	
	{	"B",					ESC_B			},	//
	{	"BT",					ESC_BT			},	//
	{	"BC",					ESC_BC			},	//
	{	"BCT",					ESC_BCT			},	//
	{	"V",					ESC_V			},	//
	{	"VT",					ESC_VT			},	//
	{	"H",					ESC_H			},	//
	{	"HT",					ESC_HT			},	//

	{	"S",					ESC_S			},	//
	{	"Z",					ESC_Z			},	//
	{	"FI",					ESC_FI			},	//
	{	"FIF",					ESC_FIF			},	//
	{	"FO",					ESC_FO			},	//
	{	"FOF",					ESC_FOF			},	//
	{	"FB",					ESC_FB			},	//
	{	"PFI",					ESC_PFI			},	//
	{	"PFO",					ESC_PFO			},	//
	{	"PWI",					ESC_PWI			},	//
	{	"PWO",					ESC_PWO			},	//

	{	"Q",					ESC_Q			},	//
	{	"F",					ESC_F			},	//

	{	"C",					ESC_C			},	//
	{	"CR",					ESC_CR			},	//
	{	"CP",					ESC_CP			},	//
	{	"CL",					ESC_CL			},	//
	{	"CY",					ESC_CY			},	//
	{	"CB",					ESC_CB			},	//
	{	"CA",					ESC_CA			},	//
	{	"CW",					ESC_CW			},	//

	{	"W",					ESC_W			},	//
	{	"WR",					ESC_WR			},	//
	{	"WN",					ESC_WN			},	//

	{	"KW",					ESC_KW			},	//
	{	"K",					ESC_K			},	//

	{	"M",					ESC_M			},	//
	{	"MS",					ESC_MS			},	//
	{	"MP",					ESC_MP			},	//
	{	"MV",					ESC_MV			},	//
	{	"MW",					ESC_MW			},	//

	{	"SE",					ESC_SE			},	//
	{	"SEP",					ESC_SEP			},	//
	{	"SES",					ESC_SES			},	//
	{	"SEW",					ESC_SEW			},	//
	{	"SEV",					ESC_SEV			},	//
	{	"SEVW",					ESC_SEVW		},	//

	{	"VV",					ESC_VV			},	//
	{	"VA",					ESC_VA			},	//
	{	"VB",					ESC_VB			},	//
	{	"VC",					ESC_VC			},	//
	{	"VX",					ESC_VX			},	//
	{	"VW",					ESC_VW			},	//
	{	"VS",					ESC_VS			},	//
	{	"VI",					ESC_VI			},	//

	{	"R",					ESC_R			},	//
	{	"RC",					ESC_RC			},	//
	{	"RR",					ESC_RR			},	//

	{	"LF",					ESC_LF			},	//

	{	"WE",					ESC_WE			},	//
	{	"WER",					ESC_WER			},	//

//低レベル関数
	{	"SetFlag",				ESC_SETFLAG			},	//
	{	"GetFlag",				ESC_GETFLAG			},	//

	{	"SetGameFlag",			ESC_SETGAMEFLAG		},	//
	{	"GetGameFlag",			ESC_GETGAMEFLAG		},	//

	{	"LoadScript",			ESC_LOADSCRIPT		},	//
	{	"GameEnd",				ESC_GAMEEND			},	//
	{	"CallFunc",				ESC_CALLFUNC		},	//

	{	"SetTimeMode",			ESC_SETTIMEMODE		},	//
	{	"SetChromaMode",		ESC_SETCHROMAMODE	},	//
	{	"SetEffctMode",			ESC_SETEFFCTMODE	},	//

	{	"SetMessage",			ESC_SETMESSAGE		},	//
	{	"SetMessage2",			ESC_SETMESSAGE2		},	//
	{	"SetMessageEx",			ESC_SETMESSAGEEX	},	//
	{	"SetChipMessage",		ESC_SETCHIPMESSAGE	},	//
	
	{	"AddMessage",			ESC_ADDMESSAGE		},	//
	{	"AddMessage2",			ESC_ADDMESSAGE2		},	//
	{	"SetMessageWait",		ESC_SETMESSAGEWAIT	},	//
	{	"ResetMessage",			ESC_RESETMESSAGE	},	//

	{	"WaitKey",				ESC_WAITKEY			},	//

	{	"SetSelectMes",			ESC_SETSELECTMES	},	//
	{	"SetSelectMesEx",		ESC_SETSELECTMESEX	},	//
	{	"SetSelect",			ESC_SETSELECT		},	//
	{	"SetSelectEx",			ESC_SETSELECTEX		},	//

	{	"PlayBgm",				ESC_PLAYBGM			},	//
	{	"PlayBgmEx",			ESC_PLAYBGMEX		},	//
	{	"StopBgm",				ESC_STOPBGM			},	//
	{	"StopBgmEx",			ESC_STOPBGMEX		},	//
	{	"SetVolumeBgm",			ESC_SETVOLUMEBGM	},	//
	{	"SetVolumeBgmEx",		ESC_SETVOLUMEBGMEX	},	//

	{	"PlaySe",				ESC_PLAYSE			},	//
	{	"PlaySeEx",				ESC_PLAYSEEX		},	//
	{	"StopSeEx",				ESC_STOPSEEX		},	//
	{	"SetVolumeSe",			ESC_SETVOLUMESE		},	//

	{	"SetWeather",			ESC_SETWEATHER		},	//
	{	"ChangeWeather",		ESC_CHANGEWEATHER	},	//
	{	"ResetWeather",			ESC_RESETWEATHER	},	//
	{	"SetLensFrea",			ESC_SETLENSFREA		},	//
	{	"SetWavEffect",			ESC_SETWAVEFFECT	},	//
	{	"ResetWavEffect",		ESC_RESETWAVEFFECT	},	//

	{	"SetWarp",				ESC_SETWARP			},	//
	{	"ResetWarp",			ESC_RESETWARP		},	//

	{	"WaitFrame",			ESC_WAITFRAME		},	//

	{	"SetBmp",				ESC_SETBMP			},	//
	{	"SetBmpEx",				ESC_SETBMPEX		},	//
	{	"SetBmp4Bmp",			ESC_SETBMP4BMP		},	//
	{	"SetBmpPrim",			ESC_SETBMPPRIM		},	//
	{	"ResetBmp",				ESC_RESETBMP		},	//
	{	"ResetBmpAll",			ESC_RESETBMPALL		},	//
	{	"SetBmpAnime",			ESC_SETBMPANIME		},	//
	{	"ResetBmpAnime",		ESC_RESETBMPANIME	},	//
	{	"WaitBmpAnime",			ESC_WAITBMPANIME	},	//
	{	"SetBmpAnimePlay",		ESC_SETBMPANIMEPLAY	},
	
	{	"SetAvi",				ESC_SETAVI			},	//
	{	"ResetAvi",				ESC_RESETAVI		},	//
	{	"WaitAvi",				ESC_WAITAVI			},	//
	{	"SetAviFull",			ESC_SETAVIFULL		},	//
	{	"WaitAviFull",			ESC_WAITAVIFULL		},	//

	{	"SetBmpDisp",			ESC_SETBMPDISP		},	//
	{	"SetBmpLayer",			ESC_SETBMPLAYER		},	//
	{	"SetBmpParam",			ESC_SETBMPPARAM		},	//
	{	"SetBmpRevParam",		ESC_SETBMPREVPARAM	},	//
	{	"SetBmpBright",			ESC_SETBMPBRIGHT	},	//
	{	"SetBmpMove",			ESC_SETBMPMOVE		},	//
	{	"SetBmpPos",			ESC_SETBMPPOS		},	//
	{	"SetBmpZoom",			ESC_SETBMPZOOM		},	//
	{	"SetBmpZoom2",			ESC_SETBMPZOOM2		},	//

	{	"SetTitle",				ESC_SETTITLE		},	//
	{	"SetEnding",			ESC_SETENDING		},	//
	{	"NextGameStep",			ESC_NEXTGAMESTEP	},	//

	{	"SetDemoFlag",			ESC_SETDEMOFLAG		},	//
	{	"SetSceneNo",			ESC_SETSCENENO		},	//
	{	"SetEndingNo",			ESC_SETENDINGNO		},	//
	{	"SetReplayNo",			ESC_SETREPLAYNO		},	//

	{	"SetSoundEvent",		ESC_SETSOUNDEVENT	},	//
	{	"SetSoundEventVolume",	ESC_SETSOUNDEVENTVOLUME	},	//

	{	"SetPotaPota",			ESC_SETPOTAPOTA		},	//

	{	"GetTime",				ESC_GETTIME			},	//
	{	"WaitTime",				ESC_WAITTIME		},	//

	{	"SetTextFormat",		ESC_SETTEXTFORMAT	},	//
	{	"SetTextSync",			ESC_SETTEXTSYNC		},	//		
	{	"SetText",				ESC_SETTEXT			},	//
	{	"SetTextEx",			ESC_SETTEXTEX		},	//
	{	"ResetText",			ESC_RESETTEXT		},	//
	{	"WaitText",				ESC_WAITTEXT		},	//
	{	"ResetTextAll",			ESC_RESETTEXTALL	},	//

	{	"SetDemoFadeFlag",		ESC_SETDEMOFADEFLAG	},	//

	{	"Mov2",					ESC_MOV2			},	//
	{	"Sin",					ESC_SIN				},	//
	{	"Cos",					ESC_COS				},	//
	{	"Abs",					ESC_ABS				},	//

	{	"TestSetParam",			ESC_TESTSETPARAM	},	//
	{	"SetPartyChar",			ESC_SETPARTYCHAR	},	//

	{	"GetPartyLevel",		ESC_GETPARTYLEVEL	},
	{	"SetMapBox",			ESC_SETMAPBOX		},

	{	"SetCutCut",			ESC_SETCUTCUT		},	//


	{	"SetNoise",				ESC_SETNOISE		},	//
	{	"T",					ESC_T				},	//
	{	"SetUsoErr",			ESC_SETUSOERR		},	//
	{	"LoadScriptNum",		ESC_LOADSCRIPTNUM	},	//

	{	"SetRipple",			ESC_SETRIPPLE		},	//
	{	"SetRippleSet",			ESC_SETRIPPLESET	},	//
	{	"WaitRipple",			ESC_WAITRIPPLE		},	//
	{	"SetRippleLost",		ESC_SETRIPPLELOST	},	//
	{	"MLW",					ESC_MLW				},	//

	{	"GetItem",				ESC_GET_ITEM		},	//
	{	"CheckItem",			ESC_CHECK_ITEM		},	//

	{	"SetMapCharName",		ESC_SET_MAP_CHAR_NAME	},	//
	{	"SetBmpRoll",			ESC_SETBMPROLL			},	//


	{	"SetMovie",				ESC_SETMOVIE		},	//
	{	"DebugBox",				ESC_DEBUGBOX		},	//
	

	{	"VHFlag",				ESC_VHFLAG			},	//

	{	NULL,	ESC_OPR_MAX	},
};
//#endif//MODE

#define ESC_NOT		0	//　未使用
#define ESC_ASC		1	//　直値（アスキーコード）
#define ESC_NUM		2	//　数値orレジスタ
#define ESC_STR		3	//　文字列
#define ESC_STR2	4	//　ベタ文字列
#define ESC_REG		5	//　レジスタに取得
#define ESC_CMP		6	//　条件式
#define ESC_ADD		7	//　ADDフラグ
#define ESC_CNT		8	//  センテンスカウンタ
#define ESC_VCNT	9	//  センテンスカウンタ

#define ESC_WAIT	0	//　
#define ESC_NOWAIT	1	//　

//#ifndef MODE

//命令構造体
typedef struct{
	char	type[15];		//引数タイプ
	char	ret;			//ESC_NOWAIT / ESC_WAIT
	char	default_num;	//デフォルト引数の数
}ESCRIPT_OPR;

ESCRIPT_OPR		EScroptOpr[] = {
/*EScroptOpr_Start*/
	{//	ESC_LOAD_MAP
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RELEASE_MAP
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//ESC_SET_MAP_OBJ
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//ESC_SET_MAP_OBJ_EX
		{ESC_NUM, ESC_STR, ESC_STR, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//ESC_SET_MAP_OBJ_NOLOAD
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},

	{//ESC_SET_MAP_OBJ_REV
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SET_MAP_OBJ_LAYER
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SET_MAP_OBJ_MOVE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SET_MAP_OBJ_ZOOM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SET_MAP_OBJ_PARAM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//ESC_PLAY_MAP_OBJ
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_RESET_MAP_OBJ
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},

	{//ESC_SET_BRIGHT_MAP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//ESC_SET_SCROLL_MAP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//ESC_SET_SCROLL_MAP_CHAR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//ESC_WAIT_MAP
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	

	{//	ESC_START_BATTLE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},
	{//	ESC_WAIT_BATTLE_END
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_WAIT_BATTLE_END_EX
		{ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//ESC_SET_MAP_CHAR_PLAER
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//ESC_SET_MAP_CHAR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//ESC_SET_MAP_CHAR_ENGUN
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//ESC_SET_MAP_CHAR_ITEM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	
	{//ESC_SET_MAP_CHAR_THINK
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//ESC_RESET_MAP_CHAR
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_RESET_MAP_CHAR_ALL
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SET_MAP_CHAR_EVENT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//ESC_WAIT_MAP_CHAR_EVENT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//ESC_SET_MAP_CHAR_MOVE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//ESC_WAIT_MAP_CHAR_MOVE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//ESC_SET_MAP_CHAR_DISP
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	
	{//	ESC_B
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_BT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_BC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_BCT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_V
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_VT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_H
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_HT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},

	{//	ESC_S
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_Z
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FI
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FIF
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FO
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FOF
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_FB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_PFI
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_PFO
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_PWI
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_PWO
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},

	{//	ESC_Q
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_F
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_C
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 7
	},
	{//	ESC_CR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_CP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_CL
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_CY
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_CB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_CA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_CW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_W
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_WR
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_WN
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},

	{//	ESC_KW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_K
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
	 	 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_M
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_MS
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_MP
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_MV
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_MW
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_SE
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SEP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_SES
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SEW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SEV
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SEVW
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	
	{//	ESC_VV
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},
	{//	ESC_VA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},
	{//	ESC_VB
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},
	{//	ESC_VC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_VCNT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},

	{//	ESC_VX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_VW
		{ESC_NOT, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_VS
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_VI
		{ESC_VCNT, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},


	{//	ESC_R
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RR
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_LF
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_WE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_WER
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_GETFLAG
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//ESC_SETGAMEFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_GETGAMEFLAG
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_LOADSCRIPT
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_GAMEEND
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_CALLFUNC
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM},
		ESC_NOWAIT, 14
	},

	{//	ESC_SETTIMEMODE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SETCHROMAMODE
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETEFFCTMODE
		{ESC_STR, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},

	{//	ESC_SETMESSAGE
		{ESC_NUM, ESC_STR, ESC_CNT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETMESSAGE2
		{ESC_STR2,ESC_ADD, ESC_CNT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETMESSAGEEX
		{ESC_NUM, ESC_NUM, ESC_STR, ESC_NUM, ESC_CNT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETCHIPMESSAGE
		{ESC_STR, ESC_CNT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_ADDMESSAGE
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_ADDMESSAGE2
		{ESC_STR2,ESC_ADD, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETMESSAGEWAIT, 0
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RESETMESSAGE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	
	{//	ESC_WAIT, 0KEY
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_SETSELECTMESSAGE
		{ESC_STR, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_SETSELECTMESSAGEEX
		{ESC_STR, ESC_STR, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETSELECT
		{ESC_REG, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},
	{//	ESC_SETSELECTEX
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
//サウンド関連
	{//	ESC_PLAYBGM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_PLAYBGMEX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_STOPBGM
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_STOPBGMEX
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETVOLUMEBGM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETVOLUMEBGMEX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_PLAYSE
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_PLAYSEEX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_STOPSEEX
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETVOLUMESE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
//その他
	{//	ESC_SETWEATHER
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_CHANGEWEATHER
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_RESETWEATHER
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETLENSFREA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETWAVEFFECT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 3
	},
	{//	ESC_RESETWAVEFFECT
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETWARP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 8
	},
	{//	ESC_RESETWARP
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 1
	},

	{//	ESC_WAITFRAME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_SETBMP
		{ESC_NUM, ESC_STR, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_STR, ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},
	{//	ESC_SETBMPEX
		{ESC_NUM, ESC_NUM, ESC_STR, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETBMP4BMP
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SETBMPPRIM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETBMP
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETBMPALL
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPANIME
		{ESC_NUM, ESC_STR, ESC_NUM, ESC_STR, ESC_NUM,
		 ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	{//	ESC_RESETBMPANIME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITBMPANIME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETBMPANIMEPLAY
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 3
	},
	
	{//	ESC_SETAVI,
		{ESC_NUM, ESC_STR, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_RESETAVI,
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITAVI,
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETAVIFULL
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_WAITAVIFULL
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_SETBMPDISP
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPLAYER
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPPARAM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SETBMPREVPARAM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPBRIGHT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//	ESC_SETBMPMOVE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPPOS
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPZOOM
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPZOOM2
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETTITLE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETENDING
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	
	{//	ESC_NEXTGAMESTEP
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},

	{//	ESC_SETDEMOFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETSCENENO
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETENDINGNO
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETREPLAYNO
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	
	{//	ESC_SETSOUNDEVENT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 5
	},

	{//	ESC_SETSOUNDEVENTVOLUME
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},

	{//	ESC_SETPOTAPOTA
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 3
	},

	{//	ESC_GETTIME
		{ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITTIME
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_SETTEXTFORMAT
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 10
	},
	{//	ESC_SETTEXTSYNC
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETTEXT
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETTEXTEX
		{ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RESETTEXT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_WAITTEXT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_RESETTEXTALL
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_SETDEMOFADEFLAG
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//	ESC_MOV2
		{ESC_REG, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SIN
		{ESC_REG, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_COS
		{ESC_REG, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_ABS
		{ESC_REG, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},

	{//ESC_TESTSETPARAM
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SETPARTYCHAR
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 2
	},
	{//ESC_GETPARTYLEVEL
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//ESC_SETMAPBOX
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},

	{//	ESC_SETCUTCUT
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETNOISE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 2
	},
	{//	ESC_T
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_SETUSOERR
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_LOADSCRIPTNUM
		{ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETRIPPLE
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETRIPPLESET
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},
	{//	ESC_WAITRIPPLE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_SETRIPPLELOST
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_MLW
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},

	{//	ESC_GET_ITEM
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_CHECK_ITEM
		{ESC_NUM, ESC_REG, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SET_MAP_CHAR_NAME
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
	{//	ESC_SETBMPROLL
		{ESC_NUM, ESC_NUM, ESC_NUM, ESC_NUM, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},


	{//	ESC_SETMOVIE
		{ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_WAIT, 0
	},
	{//	ESC_DEBUGBOX
		{ESC_NUM, ESC_STR, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 1
	},

	{//	ESC_VHFLAG
		{ESC_NUM, ESC_NUM, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT,
		 ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT, ESC_NOT},
		ESC_NOWAIT, 0
	},
};

//#endif//MODE

#endif //_ESC_H__
